name: Build G071

on:
  push:
  workflow_dispatch:   # adds a manual "Run workflow" button

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Install ARM toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-none-eabi make

      - name: Build
        run: make AM32_YOURBOARD_G071

      - name: Upload firmware
        uses: actions/upload-artifact@v5
        with:
          name: firmware
          path: obj/*.hex
